version: "3.3"

services:
  camagru:
    build: ./
    ports:
      - 8080:80
      - 1080:1080
      - 443:443
    volumes:
      - ./:/app
      - database:/var/lib/mysql
    environment:
      MYSQL_ADMIN_PASS: toor
volumes:
  database:
